// src/components/links.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import axios from "axios";

const isLoading = ref<boolean>(true);
const links = ref<Array<Link>>([]);

type Link = {
  name: string;
  site: string;
  siteURL: string;
  icon: string;
};

const loadData = () => {
  var json_file = "/assets/myLinks.json";
  axios
    .get(json_file)
    .then(
      (resp: {
        data: { name: string; site: string; siteURL: string; icon: string }[];
      }) => {
        links.value = resp.data;
        isLoading.value = false;
      }
    );
};

onMounted(() => {
  loadData();
});
</script>

<template>
  <div>
    <p class="text-xs text-right">
      📧:
      <a class="link" href="mailto:chzang55@gmail.com">chzang55@gmail.com</a>
    </p>
    <br />
    <div v-if="isLoading">
      <p class="text-center">列表戴入中，請稍等戴入……</p>
    </div>
    <div v-else class="grid grid-cols-1 gap-3.5 md:grid-cols-2 mb-3">
      <div v-for="(card, index) in links" class="card-hover">
        <a :href="card.siteURL">
          <div
            class="relative overflow-hidden border-b-2 border-r-2 border-main avatar_img"
          >
            <img
              v-if="card.icon === ''"
              class="absolute h-full"
              src="../assets/images/default.jpg"
              :id="'avatar' + index"
              :alt="'avatar' + card.name"
            />
            <img
              v-else
              class="absolute h-full"
              :src="card.icon"
              :id="'avatar' + index"
              :key="index"
              :alt="'avatar' + card.name"
            />
            <div class="min-w-0 py-5 pl-28 pr-5">
              <div
                class="text-slate-900 font-medium text-sm sm:text-base truncate dark:text-slate-200"
              >
                {{ card.name }}
              </div>
              <div
                class="text-slate-500 font-medium text-sm sm:text-base leading-tight truncate dark:text-slate-400"
              >
                {{ card.site }}
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</template>

<style scoped>
.card-hover {
  position: relative;
  transform: translateY(0);
  transition: all 0.3s ease;
}

.card-hover:hover {
  transform: translateY(-5px);
}
</style>

// src/components/react/Links.tsx
import axios from "axios";
import React, { useEffect, useState } from "react";

interface Link {
  name: string;
  site: string;
  siteURL: string;
  icon: string;
}

const cardHoverStyle: React.CSSProperties = {
  position: "relative",
  transform: "translateY(0)",
  transition: "all 0.3s ease",
};

const LinksComponent: React.FC = () => {
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [links, setLinks] = useState<Link[]>([]);

  useEffect(() => {
    const loadData = async (): Promise<void> => {
      try {
        const json_file = "/assets/myLinks.json";
        const response = await axios.get<Link[]>(json_file);
        setLinks(response.data);
        setIsLoading(false);
      } catch (error) {
        console.error("Error loading data:", error);
        setIsLoading(false);
      }
    };

    loadData();
  }, []);

  return (
    <div>
      <p className="text-right text-xs">
        📧:
        <a className="link" href="mailto:chzang55@gmail.com">
          chzang55@gmail.com
        </a>
      </p>
      <br />
      {isLoading ? (
        <p className="text-center">列表載入中，請稍等載入……</p>
      ) : (
        <div className="mb-3 grid grid-cols-1 gap-3.5 md:grid-cols-2">
          {links.map((card, index) => (
            <div
              key={index}
              style={cardHoverStyle}
              onMouseOver={e =>
                (e.currentTarget.style.transform = "translateY(-5px)")
              }
              onMouseOut={e =>
                (e.currentTarget.style.transform = "translateY(0)")
              }
            >
              <a href={card.siteURL}>
                <div className="border-main avatar_img relative overflow-hidden border-r-2 border-b-2">
                  <img
                    className="absolute h-full"
                    src={card.icon || "../assets/images/default.jpg"}
                    id={`avatar${index}`}
                    alt={`avatar${card.name}`}
                  />
                  <div className="min-w-0 py-5 pr-5 pl-28">
                    <div className="truncate text-sm font-medium text-slate-900 sm:text-base dark:text-slate-200">
                      {card.name}
                    </div>
                    <div className="truncate text-sm leading-tight font-medium text-slate-500 sm:text-base dark:text-slate-400">
                      {card.site}
                    </div>
                  </div>
                </div>
              </a>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default LinksComponent;
